import React from 'react'

export default function page() {
  return (
    <div>
        <h1 className=' text-3xl text-gray-500 my-8'>Admin Home</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet fugiat consequatur amet ipsam vitae omnis iure perferendis natus rem maiores iusto mollitia libero, officia possimus, quasi delectus dolorum maxime itaque eos commodi earum error quibusdam. Hic, modi! Fugit inventore culpa est! Illum vitae quis repellendus aut optio accusantium eum labore ipsum minima sint itaque eius qui assumenda numquam, ducimus non dolorem veritatis ex animi velit vel accusamus! Tempora accusantium reiciendis nulla repudiandae, tempore incidunt. Architecto similique consequatur beatae iure quae maxime voluptates, porro aperiam, maiores consequuntur minus minima sint reiciendis magnam, quos consectetur corrupti. Minima minus voluptatem praesentium voluptatibus corporis id iusto omnis totam facilis animi debitis quaerat ipsum, rem, et repellat quam? Voluptatibus enim voluptatum tenetur ea temporibus id inventore autem. Atque asperiores ut maiores nihil, dignissimos quibusdam doloribus itaque cumque quisquam amet veritatis fuga saepe. Accusantium vero cum error numquam magnam quidem placeat corrupti tenetur. Earum exercitationem in sequi ex voluptates, amet assumenda, id aspernatur odio atque facilis nulla laudantium necessitatibus placeat, inventore qui quia nam hic deleniti reiciendis quos sit. Tempore dolore suscipit animi atque accusantium dicta quasi nostrum rem? Vitae fugiat quos ipsam esse consequatur, unde tempora commodi reiciendis neque omnis. Dignissimos aperiam nihil excepturi porro, ab quasi fugiat harum, ad corporis qui quia ex sapiente repellat alias? Unde obcaecati eaque modi incidunt commodi possimus animi delectus magnam quasi dolore, exercitationem eos, natus dolorem corrupti amet tempore, necessitatibus officiis ea veniam earum voluptate ex? Enim, perferendis quibusdam ea id iure corporis reprehenderit vitae aliquam quod, vero, veniam optio. Consequuntur exercitationem voluptate illum quae, repudiandae dolor reiciendis placeat ducimus tenetur velit. Inventore nesciunt cumque dolor ea neque eius sapiente, eveniet consequatur optio quae minima veritatis! Sunt, voluptas eligendi nemo repudiandae magnam debitis, minus provident vitae, temporibus repellat nisi vel fuga velit nulla tempore soluta quibusdam. Error, autem.</p>
    </div>
  )
}
